services:

  backend:
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000


  frontend:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.nuxt
    ports:
      - "3000:3000"
    command: npm run dev

  caddy:
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile:ro