services:

  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"



  frontend:
    build:
      context: ./frontend
    volumes:
      - /app/node_modules
    expose:
      - "3000"



  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./caddy/Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - static_data:/app/staticfiles:ro
      - media_data:/app/media:ro
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    depends_on:
      - frontend
      - backend


volumes:

  postgres_data:
  media_data:
  static_data:
  caddy_data:
  caddy_config:
  caddy_logs: