name: belovedbully

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - static-data:/app/staticfiles
      - media-data:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - memcached

  db:
    image: postgres:17
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

  memcached:
    image: memcached:1.6.21

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static-data:/static:ro
      - media-data:/media:ro
    ports:
      - "8001:80"
    depends_on:
      - web

volumes:
  postgres-data:
  static-data:
  media-data: