# Generated by Django 6.0.5 on 2026-05-30 21:24

import django.db.models.deletion
import kennel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DogSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LitterMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Мальчик'), ('female', 'Девочка')], max_length=10)),
                ('status', models.CharField(blank=True, choices=[('free', 'Свободен'), ('reserved', 'Забронирован'), ('sold', 'Продан')], max_length=20, null=True)),
                ('role', models.CharField(choices=[('puppy', 'Щенок'), ('producer', 'Производитель')], max_length=20)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kennel.dogcolor')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kennel.dogsize')),
            ],
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('birth_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='litters_as_father', to='kennel.dog')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='litters_as_mother', to='kennel.dog')),
            ],
        ),
        migrations.AddField(
            model_name='dog',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puppies', to='kennel.litter'),
        ),
        migrations.CreateModel(
            name='DogMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=kennel.models.dog_media_upload_to)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('is_cover', models.BooleanField(default=False, verbose_name='Обложка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='kennel.dog')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_cover', True)), fields=('dog',), name='unique_cover_per_dog')],
            },
        ),
    ]
