# Generated by Django 6.0.5 on 2026-06-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kennel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LitterMedia',
        ),
        migrations.AddField(
            model_name='litter',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='litters/'),
        ),
    ]
