# Generated by Django 5.1.3 on 2025-04-07 22:54

import catalog.models
import django.db.models.deletion
import imagekit.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='URL')),
                ('category', models.CharField(choices=[('puppy', 'Щенок'), ('adult', 'Производитель')], max_length=10, verbose_name='Категория')),
                ('status', models.CharField(choices=[('available', 'Свободен'), ('reserved', 'Забронирован'), ('sold', 'Куплен')], max_length=10, null=True, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Кобель'), ('F', 'Сука')], max_length=1, verbose_name='Пол')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Окрас')),
                ('pedigree', models.URLField(blank=True, max_length=500, null=True, verbose_name='Родословная')),
                ('dog_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=catalog.models.DogImage.get_upload_path, verbose_name='Изображение')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.dog')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='URL')),
                ('father', models.ForeignKey(limit_choices_to={'category': 'adult', 'gender': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_litters', to='catalog.dog', verbose_name='Отец')),
                ('mother', models.ForeignKey(limit_choices_to={'category': 'adult', 'gender': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_litters', to='catalog.dog', verbose_name='Мать')),
            ],
            options={
                'verbose_name': 'Помёт',
                'verbose_name_plural': 'Помёты',
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.litter', verbose_name='Помёт'),
        ),
        migrations.CreateModel(
            name='LitterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to=catalog.models.LitterImage.get_upload_path, verbose_name='Изображение')),
                ('litter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.litter')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-id'],
            },
        ),
    ]
