# Generated by Django 5.1.3 on 2025-10-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dogimage',
            options={'ordering': ['-is_avatar', '-id'], 'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='dogimage',
            name='is_avatar',
            field=models.BooleanField(default=False, verbose_name='Аватар'),
        ),
    ]
