# Generated by Django 5.1.3 on 2025-10-26 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_dogimage_options_dogimage_is_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puppies', to='catalog.litter', verbose_name='Помёт'),
        ),
    ]
